### ISSUE TITLE
Rounding does not work (as expected)

### ISSUE THREAD

**Issue by jonira** [globalizejs/globalize#190]
Rounding does not work as expected (standard rounding to nearest number):

equal( Globalize.format(1.255, "n2"), "1.26" ); // yields 1.25 - tested on 79ae658b84

I'm not sure if this a culture issue (I'm familiar with "fi-FI") or is the default rounding mode something else than I expect (could not find info about this on the docs)

**Comment by quentindemetz** [comment]
I can't get this to work when trying whole numbers, I'm trying to accomplish the following:
```
equal(Globalize.formatNumber(100.7, {maximumFractionDigits: 2}), "101") // currently giving 100…
```
Can you give me some help? Thanks!

**Comment by rxaviers** [comment]
`Globalize.formatNumber(100.7, {maximumFractionDigits: 2})` outputs 100.7 as it should.

I guess you meant `Globalize.formatNumber(100.7, {maximumFractionDigits: 0})`. In that case, you get `100` (instead of `101` as you expect) and indeed there's no rounding made to whole numbers. I've just opened #379 to track that. Alternatively, you could round it yourself `Globalize.formatNumber(Math.round(100.7), {maximumFractionDigits: 0})` in the meanwhile.
