### ISSUE TITLE
Support for short and long decimal formatting

### ISSUE THREAD

**Issue by KL-7** [globalizejs/globalize#406]
This feature would allow abbreviating big numbers such as `1,234,567` as `1M` or `1 million`.

Short and long decimal formatting is briefly described in "Short Numbers" section of ["Number Patterns"](http://cldr.unicode.org/translation/number-patterns) and the data for it is available in [numbers.json](http://www.unicode.org/repos/cldr-aux/json/25/main/en/numbers.json).

Both formats are implemented in [twitter-cldr-js](https://github.com/twitter/twitter-cldr-js) as subclasses of [AbbreviatedNumberFormatter](https://github.com/twitter/twitter-cldr-js/blob/master/lib/twitter_cldr/js/mustache/numbers/numbers.coffee#L135-L171) if you want to check it out for reference. And the specs are over [here](https://github.com/twitter/twitter-cldr-js/tree/master/spec/js/numbers/abbreviated).

---

Edited by rxaviers:
- Related Ecma proposal https://github.com/tc39/ecma402/issues/37

**Comment by rxaviers** [comment]
:+1:

We need to brainstorm the API. Something to consider: currencies, e.g., `$1.5M`?

**Comment by M-Areeb** [comment]
can i fix this bug

**Comment by rxaviers** [comment]
@M-Areeb feel free to submit a PR with a fix.

**Comment by rxaviers** [comment]
Related Ecma proposal https://github.com/tc39/ecma402/issues/37

**Comment by necolas** [comment]
Hey, please could you give me a few pointers as to how we could get started adding this feature?

**Comment by rxaviers** [comment]
Hi @necolas!

It's great to hear from you. The first step is to define an API. Are we going to reuse number formatter? How can currency and unit formatters reuse this feature? It would be ideal to do a good research on the existing APIs&proposals elsewhere and to get it digested in here, so that we can brainstorm about it. The second step, the implementation, will depend on what we define, so as soon as we're happy with the API I can provide additional implementation pointers. Did I answer your question? Just let me know if you are looking for something else.

**Comment by necolas** [comment]
I think the ECMA proposal APIs looks good enough

**Comment by jzaefferer** [comment]
You mean this one, right?
```js
new Intl.NumberFormat('en', { compact: 'best-fit' }).format(1234000); // 1.2M
new Intl.NumberFormat('en', { compact: '4-digits' }).format(1234000); // 1234K
```
If that's "all" there is, adding an option to `numberFormatter` would be enough. The compiler should take care of removing that code when not needed.

**Comment by necolas** [comment]
Yeah, that seems sufficient for our use case

**Comment by rxaviers** [comment]
@necolas, so as next steps I suggest the following:

1. API - Update documentation (markdown files) to reflect the proposed API. Files that may be of interest are: README.md, doc/number/number-formatter.md, doc/api/currency/currency-formatter.md (that may propagate `compact` option to number formatter), doc/api/unit/unit-formatter.md (may propagate `compact` as well), and doc/api/relative-time/relative-time-formatter.md (may propagate `compact` as well).

2. Implementation + Tests - I suggest that code and tests walk together (as in TDD), I can provide further pointers after the doc above is complete.

Process wise... Feel free to submit a work in progress PR soon for early review and feedback. We can keep pushing new commits to that PR in order to get everything implemented before we land.

Please, let me know if there's anything you need from my side.

**Comment by sieverk** [comment]
@rxaviers I'm looking into implementing this. (Picking it up from @necolas.) I've gone through the short number patterns described in [Number Patterns](http://cldr.unicode.org/translation/number-patterns) and taken a look at the [referenced implementation](http://www.unicode.org/repos/cldr-aux/json/25/main/en/numbers.json) available in CLDR.

I'm thinking the API for this would be a compact option that accepts a value of "short" or "long".

```
.numberFormatter({ compact: "short" })( 14305000 )
// > "14M"

.numberFormatter({ compact: "long" })( 14305000 )
// > "14 million"
```

Most of the other options (round, style, useGrouping) should coexist peacefully with compact, though it would potentially supersede any specified minimumSignificantDigits and/or maximumSignificantDigits. It may look a bit odd with style=percent. (12K % doesn't look so bad, but 12 thousand % is eh.)

As with the other number formatter options, I think the currency and unit formatters could just pass compact through.

**Currency:**
```
formatter = Globalize.currencyFormatter( "USD", {
  compact: true
});

formatter( 12830000000 );
// > "$13B"
```

**Units:**
```
customNumberFormatter = Globalize.numberFormatter({ compact = "long" })
formatter = Globalize.unitFormatter( "year", {
	form: "long", numberFormatter: customNumberFormatter
} );

formatter(5200000)
// > "5 million years"
```

If that API sounds good, would love to chat implementation (or any proposed changes/tweaks). I'll spend some time poking around at it myself in the meantime. The main challenge I foresee is the fact that the compact pattern has to be calculated at format-time (we need to know how many digits are in the number), but the pattern string is calculated when the formatter is created using the provided options.

**Comment by Shashikoride** [comment]
Hi @rxaviers,

I am using Globalize.numberFormatter({compact:"short"}). However, I see there no change in the format of the number and no error reported in the console. 

I am using Globalize version of 1.3.0. Can you please suggest?

I see there no implementation for the compact option in the number.js file.

**Comment by rxaviers** [comment]
Compact form support added in 1.4.0. :tada:
