### ISSUE TITLE
fs.readydirSync is not a function

### ISSUE THREAD

**Issue by ibrown-gaikai** [globalizejs/globalize#567]
Using browserify, gulp, babelify I am not able to include CLDR and load into globalize.

const Globalize = require('globalize');
const GlobalizeLocalizer = require('react-widgets/lib/localizers/globalize');
const CLDR = require('cldr-data');

Globalize.load(CLDR.entireSupplemental());
    Globalize.load(CLDR.entireMainFor("en"));
    Globalize.locale('en-US');

```
GlobalizeLocalizer(Globalize);
```

The entireSupplemental() method above eventually uses fs which is an empty object. Is there something I can do to fix this? I tried brfs, but haven't had any luck

The specific error is _fs.readdirSync is not a function. This is thrown in the jsonFiles method within the CLDR entireSupplemental method.

Thank you.

**Comment by aclindsa** [comment]
I think the issue is that fs is a nodejs thing, so it won't be present in your browser. Try manually loading the cldr-data paths you need, instead of relying on the .entireSupplemental() and entireMainFor() functions. For example, do this instead:
Globalize.load(
  require("cldr-data/main/en/ca-gregorian"),
  require("cldr-data/main/en/numbers")
);
