### ISSUE TITLE
Should globalize rely on a hardcoded version of cldrjs?

### ISSUE THREAD

**Issue by miracle2k** [globalizejs/globalize#642]
I am already using cldr.js in my app, and loading CLDR data files. I wanted to add globalize to the mix and assumed that would work great, since it uses the same backend.

Indeed it does work great - with the small kink that I was using a slightly different version of cldr.js. As a result, the data loaded is not recognized by the private copy that globalize.js gets from NPM.

I was thinking that the cldr.js dependency should be made more loose.

**Comment by rxaviers** [comment]
Yeap, I think globalize should depend on a cldrjs range instead of a hardcoded version. The thing about the hardcoded version is that it's easier to assert that both globalize and cldrjs versions work fine. Anyway, it's awkward that globalize restricts the user choice of using, for example, a newer (yet compatible) version of cldrjs. We just need better tests to assert that using the cldrjs range wont break it.

**Comment by jzaefferer** [comment]
Using `^` range prefix seems reasonable, at least after releasing cldrjs 1.0.0.

**Comment by rxaviers** [comment]
This is a very small change and I plan to release it as a patch release. Feedbacks are welcome.
