### ISSUE TITLE
Complexity or Simplicity

### ISSUE THREAD

**Issue by sun21170** [globalizejs/globalize#659]
I have been trying the whole day to use this without any success. I am using this in an ASP.Net aspx page in which I am including js files using script tags.

Getting/downloading the json files is like climbing Mount Everest without oxygen since nothing in the documentation explains this clearly and then the task of finding how to load these json files is like finding a needle in haystack. _It would help a  lot  if there was a large zipped file that included all the json files and the link to this zipped file was provided in Getting Started section of documentation._
 
BUT, then I tried the older jQuery globalize version and it was too simple to use and I had a running page in under 2 minutes.

**So my question is**: What would I gain by using this ultra-complex library rather than the original jquery globalize which had me up and running in 2 minutes?  Even if I do succeed in using this library, and leave the project on completion, then I am not sure how easy/difficult maintenance of globalize in this page would be when a new developer takes over. When I used the jquery globalize plugin, I only downloaded 2 small files - jquery-glob.min.js of 12KB size and jQuery.glob.hi-IN.min.js of 1.3KB size. So, may be I am missing something which is there in newer version even though its extremely complex.

**Comment by rxaviers** [comment]
[Why Globalize?](https://github.com/globalizejs/globalize#why-globalize) has our design goals. The first three bullets are valid only for 1.x. In summary, that means to you:
- better i18n quality and coverage due to CLDR
- better control: modular features, i.e., load the code you need; no embedded data, i.e., use the CLDR version you want, the slice you want, load it the way you want, you can even override the data with business specific updates.
- better efficiency: https://github.com/globalizejs/globalize-compiler (see the README of https://github.com/rxaviers/todomvc/tree/react-globalize/examples/react-globalize for some numbers)

The easiest way to get started is https://github.com/globalizejs/globalize/tree/master/examples/app-npm-webpack

Was some of this info hard to find? Please, help us improve our docs/education. Thanks
