### ISSUE TITLE
Hello World (plain javascript) example does not work!

### ISSUE THREAD

**Issue by iamandrewluca** [globalizejs/globalize#717]
I have `index.html`, unziped `cldrjs` and `globalzie`. when I open console I get

```js
Uncaught TypeError: en.formatDateToParts is not a function
    at index.html:240
```

and I have on page block with text

```
You need to download the `cldrjs` dependency yourself. Read README.md for instructions.
```
It seems that locale does have only method `formatDate`
I commented out block
```
// Use Globalize to format dates to parts.
```
and example works

**Comment by rxaviers** [comment]
This is because `master` has additional features compared to the latest stable release. By using the examples found on `master`, you need to use equivalent globalize, which now is 1.3.0-alpha.3 https://github.com/globalizejs/globalize/archive/1.3.0-alpha.3.zip.

Please, post additional comments in case the issue still persists to you.
