### ISSUE TITLE
Where can I find the ECCN classification for Globalize 1.3.0 ?

### ISSUE THREAD

**Issue by jhaverhals** [globalizejs/globalize#786]
My company wants to start using Globalize. For this I am looking for the [ECCN classification number](https://www.bis.doc.gov/index.php/regulations/commerce-control-list-ccl) for the current latest release Globalize 1.3.0 -- but can't find it. Where should I look for it?

**Comment by rxaviers** [comment]
@scottgonzalez @kborchers have you heard of it?

**Comment by kborchers** [comment]
I will check with legal for an accurate classification since this is the first time we have had this request for Globalize.

**Comment by kborchers** [comment]
After consulting with legal, Globalize is publicly available software not subject to the Export Administration Regulations (EAR) per EAR 734.3(b) and 734.7. Because Globalize is not subject to the EAR it does not have an Export Control Classification Number (ECCN).

**Comment by scottgonzalez** [comment]
Are you sure that it doesn't have an ECCN and that it is not designated as EAR99?

**Comment by rxaviers** [comment]
Thank you @kborchers for the confirmation. @scottgonzalez, do you have any additional info?

**Comment by scottgonzalez** [comment]
I'm not a lawyer, but here's what I know:

We've been telling people for years that jQuery, which is not subject to the EAR, is designated as EAR99.

Export Control Classification Numbers (ECCNs) are part of the Export Administration Regulations (EAR) for categorizing commercial goods. The EAR is a system used by the Bureau of Industry and Security (BIS), part of the Department of Commerce, to determine the licensing regulations on exports. To determine the ECCN, you must consult the Commerce Control List (CCL). Most products are not listed in the CCL and therefore don't have an ECCN. However, they still get a designation of EAR99 to explicitly indicate that they're not controlled (you can think of this like returning a `NO_ECCN` constant as opposed to `null`). Even products with a designation of EAR99 still have regulations to follow based on factors other than the product itself, such as the country or party to which you're exporting).

Like most government text, I have trouble with the details. Here are two direct quotes:

> Many commercial goods are not on the Commerce Control List and do not have an
ECCN. These goods are designated as EAR99.

This indicates to me that if you don't have an ECCN, you are automatically designated as EAR99, which means even if you don't have an ECCN, you sort of do.

> The following are not subject to the EAR:

This indicates to me that there actually are goods that get completely excluded.

Those two statements seem contradictory to me, so I asked for clarification since responding with "no ECCN" is a divergence from the "EAR99" response we've been giving for the past several years.

**Comment by kborchers** [comment]
It is true in the past, based on the EAR as defined at that time, we recommended that jQuery be classified EAR99. After a renewed review this week, legal counsel's interpretation is that no JS Foundation projects are subject to the EAR and therefore do not get an ECCN. To quote counsel's response:

> In the case of an open source software project, where the source code is always going to be published, you’ll never fall under EAR99 then, because by default you won’t be subject to the EAR. The only situation in which you’d be subject to the EAR is if the software deals with encryption, and in that instance the ECCN would be 5D002.

**Comment by jhaverhals** [comment]
Thanks a lot @scottgonzalez, @kborchers and @rxaviers for reporting back the results of your journeys through the legal and regulation worlds.

So, with this conclusion I now can safely put 'Not applicable' in the ECCN section of Globalize in our third party products list. Thanks!

**Comment by rxaviers** [comment]
Thank you @scottgonzalez and @kborchers
