### ISSUE TITLE
Number rounding still have problems with inaccurate floating point arithmetic

### ISSUE THREAD

**Issue by DokaRus** [globalizejs/globalize#884]
@rxaviers looks like #386 only solves the problem for positive numbers.

Globalizejs v.1.4.2
![image](https://user-images.githubusercontent.com/1554153/72145423-8f033e00-33ab-11ea-9d5e-154afc15f8f5.png)

Related issues or PRs: #386 #856

**Comment by rxaviers** [comment]
The problem fixed by #386 is related to inaccurate floating point arithmetics, which doesn't happen here. The results posted here are correct. Note you can change the rounding mode if needed via [options.round](https://github.com/globalizejs/globalize/blob/master/doc/api/number/number-formatter.md#optionsround).
